export enum BUSINESS_ERROR_CODE {
  COMMON = 10001,

  INVALID_TOKEN = 20001,
  EMPTY_TOKEN = 20002,
  EXPIRED_TOKEN = 20003,

  ACCESS_FORBIDDEN = 30001,
}

export const BUSINESS_ERROR_TEXT: Record<BUSINESS_ERROR_CODE, string> = {
  [BUSINESS_ERROR_CODE.COMMON]: '服务出现错误',
  [BUSINESS_ERROR_CODE.INVALID_TOKEN]: '非法token',
  [BUSINESS_ERROR_CODE.EMPTY_TOKEN]: '空token',
  [BUSINESS_ERROR_CODE.EXPIRED_TOKEN]: 'token已过期',
  [BUSINESS_ERROR_CODE.ACCESS_FORBIDDEN]: '禁止访问',
}
